# Generated by Django 4.0.4 on 2022-06-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_category_marketitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('market_admin', 'Can access Market specific administrative sections.')]},
        ),
    ]
