# Generated by Django 4.0.4 on 2022-07-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image_file',
            field=models.ImageField(upload_to='items/'),
        ),
    ]
